### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by Ninjafartdust130** [ClayAmore/ER-Save-Editor#42] opened 2024-06-23 17:39 UTC
when i open  my save file it crashes and i was wondering if claymore or anyone is willing to make a save editor with the dlc weapons

**Comment by ClayAmore** [comment] 2024-06-23 17:52
I'm currently working on updates for the DLC that was released a few days ago. It might take some time, as I have other life obligations. If you're on PC and want to create builds more quickly, you can use the TGA table. Check out this video guide by Steelovsky: [Steelovsky's TGA Table Guide](https://youtu.be/Mg0zjM-DVqg).

If you're on PlayStation, please be patient a bit longer. I'm aiming to be thorough and fix issues that have been present since the previous version of the tool.

And please, stop posting duplicate issues! 😊

**Comment by Ninjafartdust130** [comment] 2024-06-23 17:53
thx sorry

**Comment by ClayAmore** [comment] 2024-06-23 18:26
duplicate of #43

**Closed as completed by ClayAmore** 2024-06-23 18:26 UTC
