### ISSUE TITLE
Open error

### ISSUE THREAD

**Issue by Ninjafartdust130** [ClayAmore/ER-Save-Editor#41] opened 2024-06-22 22:06 UTC
When I use the open save file thing and it crashes

**Comment by jacobthebossie** [comment] 2024-06-22 22:12
it seems to only be with PS tho the PC doesn't affect the save only the PS4 saves effect it

**Comment by mit999sif** [comment] 2024-06-22 22:22
It happened to me too, I think is for the DLC.
I use PC, I bought the game with the DLC , now that the DLC has been release the program can't handle.

**Comment by yesdog96** [comment] 2024-06-22 22:40
From what I heard Steel has a test copy of the update to the editor. Shouldn't be too long before it's updated. On Nexusmods @ClayAmore has said that he's working on the update. If you look at the files here it's been updated yesterday.

**Comment by jacobthebossie** [comment] 2024-06-22 22:53
> From what I heard Steel has a test copy of the update to the editor. Shouldn't be too long before it's updated. On Nexusmods @ClayAmore has said that he's working on the update. If you look at the files here it's been updated yesterday. 

think it'll be done by tomorrow?

**Comment by yesdog96** [comment] 2024-06-22 23:15
No idea. Cheat engine tables were just updated partially. Steel has not streamed at all today, so I assume they're either working on it or taking a day off.

**Comment by ClayAmore** [comment] 2024-06-23 18:26
duplicate of #43

**Comment by ClayAmore** [comment] 2024-06-23 18:27
duplicate of #43

**Closed as completed by ClayAmore** 2024-06-23 18:27 UTC
