### ISSUE TITLE
Editor Crashes upon loading a save

### ISSUE THREAD

**Issue by StoneKill** [ClayAmore/ER-Save-Editor#65] opened 2024-07-16 09:04 UTC
During the process of me loading a save :
 - Game is in version app version 1.12.3
 - Game is in calibration version 1.12.4
 - DLC is installed
 - When I load the save, Steam is fully closed and not running in the backgroud
The crash does not show any error messages, it just outright closes

**Comment by EthanShoeDev** [comment] 2024-07-16 17:12
Duplicate #43

**Comment by nozwock** [comment] 2024-07-16 18:12
> The crash does not show any error messages, it just outright closes

It'll show it if you were to run it from the terminal, but only for the debug build, not really ideal. Currently, they've opted to crash the program rather than show an error message in the GUI since it's less work.

**Comment by nozwock** [comment] 2024-07-16 18:28
Also a duplicate of #56

**Comment by renatopontes** [comment] 2024-07-28 17:02
I had this problem today and did some digging. While reading the save file, the code was reading some insanely large value for the projectile_count of a character and then went out of bounds in the next for loop:

```rust
// Distinct Projectile Count
equip_projectile_data.projectile_count = br.read_i32()?; // was reading something like 16980419

// Quick slot items
for _i in 0..equip_projectile_data.projectile_count { // obviously crashed
    equip_projectile_data.projectiles.push(EquipProjectile::read(br)?);
}
```

After some investigation, my theory is that the game only updates the character data in the save file when that character has been loaded after the update.
So, what fixed it for me was **opening the game and then loading each character that I hadn't used since the DLC update**. Upon loading, these characters receive the new gesture and get a tutorial pop up about the new inventory tab.
After that, the code was able to load the file correctly instead of panicking.

(tested on master version at 014107f0, not on release 0.0.21)

**Comment by ClayAmore** [comment] 2024-08-12 06:03
I'll close this as a duplicate of #43 . There's a bunch of forks with hot fixes for different versions of the game.

**Closed as completed by ClayAmore** 2024-08-12 06:03 UTC
