### ISSUE TITLE
Crashes on opening file (release/0.1.0 branch, w/ error) 

### ISSUE THREAD

**Issue by iMakeMehPrograms** [ClayAmore/ER-Save-Editor#74] opened 2024-08-12 02:51 UTC
Essentially, when opening my save file: 
[er-sav.zip](https://github.com/user-attachments/files/16576957/er-sav.zip)
The following error occurs:
```
assertion `left == right` failed
right = 135
left = 0
```
The line it points to is in ```src\user_data_11.rs```, in this function:
```
impl Read for UserData11 {
    fn read(br: &mut BinaryReader) -> Result<UserData11, Error> {
        let mut user_data_11 = UserData11::default();
        user_data_11.unk.copy_from_slice(br.read_bytes(0x10)?);
        user_data_11.regulation.copy_from_slice(br.read_bytes(0x1e9fb0)?);
        user_data_11.rest.copy_from_slice(br.read_bytes(0x56050)?);
        assert_eq!(user_data_11.rest[0], 0); // ERR
        Ok(user_data_11)
    }
}
```
I can provide partial or full backtrace if needed. 
Extra info:
App ver 1.13
Calibration ver 1.13.2
SOTE installed
Both characters (lvl 9 & lvl 149) have been opened on latest patch + with SOTE

**Comment by iMakeMehPrograms** [comment] 2024-08-12 02:53
In terms of what I'm trying to do; I'm just trying to get the final ending after beating radagon because I lost the save pre-ending

**Comment by ClayAmore** [comment] 2024-08-12 05:34
`src\user_data_11.rs` and the code snippet is not from the 0.1.0 branch, but I updated the latest lib to support the latest regulation. If you build the branch you should be able to read the save file. There's a bunch of still not implemented in this version though.

**Comment by ClayAmore** [comment] 2024-08-12 05:39
duplicate of #72

**Closed as completed by ClayAmore** 2024-08-12 05:39 UTC

**Comment by iMakeMehPrograms** [comment] 2024-08-12 14:03
Thanks!
