### ISSUE TITLE
PS4 saves open error

### ISSUE THREAD

**Issue by xxxx0107** [ClayAmore/ER-Save-Editor#38] opened 2024-06-22 03:50 UTC
Save file has irregular data!
[memory.zip](https://github.com/user-attachments/files/15934978/memory.zip)

**Comment by jacobthebossie** [comment] 2024-06-22 17:14
When will this be fixed im tryna play the dlc without my level 1 account):

**Comment by ClayAmore** [comment] 2024-06-23 18:28
duplicate of #43

**Closed as completed by ClayAmore** 2024-06-23 18:28 UTC
