### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by Ninjafartdust130** [ClayAmore/ER-Save-Editor#39] opened 2024-06-22 13:53 UTC
Hi is it possible u can make the save editor with the new dlc weapons

**Comment by R0yl** [comment] 2024-06-22 14:44
Waiting for the update too, for crying out aloud

**Comment by jacobthebossie** [comment] 2024-06-22 15:03
what do you mean update please i thought you were the dude to make it work???

**Comment by jacobthebossie** [comment] 2024-06-22 15:19
> Waiting for the update too, for crying out aloud
> 
> 

what update is it for the save editor???

**Comment by Ninjafartdust130** [comment] 2024-06-22 15:34
Yes I want one for the save editor so we can get dlc weapons

**Comment by jacobthebossie** [comment] 2024-06-22 15:41
> Yes I want one for the save editor so we can get dlc weapons 

but what if you don't have the dlc can you still use save editor??

**Comment by Ninjafartdust130** [comment] 2024-06-22 15:50
I think I got dlc weapons from friends

**Comment by jacobthebossie** [comment] 2024-06-22 15:53
> I think I got dlc weapons from friends

do you have the DLC?

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:05
I don't no

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:05
People gave me some though

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:07
Some dlc weapons

**Comment by jacobthebossie** [comment] 2024-06-22 16:14
> Some dlc weapons 

do you have any idea when they will update this?

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:16
No I don't I was asking for one

**Comment by jacobthebossie** [comment] 2024-06-22 16:26
> No I don't I was asking for one

is your save editor working on console???

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:43
Yes

**Comment by Ninjafartdust130** [comment] 2024-06-22 16:44
I use a discord bot that description like save wizard it's free look it up

**Comment by jacobthebossie** [comment] 2024-06-22 16:46
> I use a discord bot that description like save wizard it's free look it up

do you mind adding me on discord and sending me the link my user is mhmjacob

**Comment by jacobthebossie** [comment] 2024-06-22 16:49
> I use a discord bot that description like save wizard it's free look it up

also i already have save wizard so i shouldn't need it free it's just that my save editor for elden ring keeps crashing whenever i put in the txt file and it's really bugging me out

**Comment by jacobthebossie** [comment] 2024-06-22 17:15
im so confused how did you get console to work its not working for me

**Comment by carloslos** [comment] 2024-06-23 02:25
This is not a forum, don't open useless issues just begging, geeeeeez.

**Comment by Ninjafartdust130** [comment] 2024-06-23 02:29
Womp womp

**Comment by ClayAmore** [comment] 2024-06-23 18:29
duplicate of #43

**Closed as completed by ClayAmore** 2024-06-23 18:29 UTC
