### ISSUE TITLE
New version savefiles crashes instant  

### ISSUE THREAD

**Issue by muesli-dev** [ClayAmore/ER-Save-Editor#32] opened 2024-06-20 12:19 UTC
cant open any savefile created after 19.06.2024 (after the dlc pre patch)

**Comment by LilOhGee** [comment] 2024-06-20 16:10
I can confirm this is happening on my side too, my backup file from before patch still work.

**Comment by elendil7** [comment] 2024-06-20 23:26
+1, happening on my end too, instant crash on save file load

**Comment by irxnbxy** [comment] 2024-06-21 06:54
can i have the file from before patch?

**Comment by jacobthebossie** [comment] 2024-06-21 22:44
Im on playstation on version 1.0 and i cant edit mine for some reason 
idk why

**Comment by ClayAmore** [comment] 2024-06-23 18:28
duplicate of #43

**Closed by ClayAmore** 2024-06-23 18:28 UTC
