### ISSUE TITLE
DLC Update, Posibility to remove item from inventory + BUG

### ISSUE THREAD

**Issue by concave5635** [ClayAmore/ER-Save-Editor#46] opened 2024-06-24 23:19 UTC
Hello,

I added 999 Tier 8 smithing stones to my inventory using a save editor, but they are not showing up in the game. Moreover, my save file seems to be corrupted now: I cannot remove the stones, nor can I use them, as the game does not recognize their presence even though the save editor shows they are there. Could you please add an option to remove items from the inventory in the save editor?

Also, can you please add a new DLC items to the editor?

**Comment by TkMatt** [comment] 2024-06-26 06:10
I wanted to clean a save file too from all dlc items, gonna wait for update i guess

**Comment by ClayAmore** [comment] 2024-08-12 06:00
Noted. I'll see how viable it is to make items removeable.

**Comment by ClayAmore** [comment] 2024-08-12 06:09
duplicate of #35

**Closed as completed by ClayAmore** 2024-08-12 06:09 UTC
Labels: enhancement
