### ISSUE TITLE
Crashes upon loading file

### ISSUE THREAD

**Issue by BeyyTU** [ClayAmore/ER-Save-Editor#75] opened 2024-08-12 07:38 UTC
Game is up to date and all files have been verified, Launching with a current file that has been ran through the DLC. No info on whats happening, just insta crash. Will post a clip to ensure im not a moron with sleep deprivation.

First time using aswell so apologies if I am doing something incorrect, but from past experience with duping and save editing, seems fine.

https://github.com/user-attachments/assets/8e64f63e-110a-409a-8115-ff45eb32c70a

**Comment by ClayAmore** [comment] 2024-08-12 08:38
Yeah. Some offsets changed in the DLC and this version does not handle errors well enough. There's a few forks with some hot fixes and I'm working on a new release.

duplicate of #43

**Comment by ClayAmore** [comment] 2024-08-12 08:39
I'll close this issue as a duplicate of #43

**Closed as completed by ClayAmore** 2024-08-12 08:39 UTC
